/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"

bool_t
xdr_entrada (XDR *xdrs, entrada *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->operando1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->operando2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->operacion))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_salida (XDR *xdrs, salida *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->resultado))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->resultado2))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->mensaje, 255,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
