/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

salida *
suma_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static salida  result;

	int operando1 = argp ->operando1;
	int operando2 = argp ->operando2;
	result.resultado = operando1+operando2;
	

	return &result;
}

salida *
resta_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static salida  result;

	int operando1 = argp ->operando1;
	int operando2 = argp ->operando2;
	result.resultado = operando1-operando2;

	return &result;
}

salida *
multiplicacion_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static salida  result;

	int operando1 = argp ->operando1;
	int operando2 = argp ->operando2;
	result.resultado = operando1*operando2;

	return &result;
}

salida *
division_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static salida  result;

	int operando1 = argp ->operando1;
	int operando2 = argp ->operando2;
	result.resultado = operando1 / operando2;
	result.resultado2 = operando1 % operando2;

	return &result;
}
