/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct entrada {
	int operando1;
	int operando2;
	int operacion;
};
typedef struct entrada entrada;

struct salida {
	int resultado;
	int resultado2;
	char mensaje[255];
};
typedef struct salida salida;

#define CALCULADORA_PROGRAMA 0x20000001
#define CALCULADORA_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUMA 1
extern  salida * suma_1(entrada *, CLIENT *);
extern  salida * suma_1_svc(entrada *, struct svc_req *);
#define RESTA 2
extern  salida * resta_1(entrada *, CLIENT *);
extern  salida * resta_1_svc(entrada *, struct svc_req *);
#define MULTIPLICACION 3
extern  salida * multiplicacion_1(entrada *, CLIENT *);
extern  salida * multiplicacion_1_svc(entrada *, struct svc_req *);
#define DIVISION 4
extern  salida * division_1(entrada *, CLIENT *);
extern  salida * division_1_svc(entrada *, struct svc_req *);
extern int calculadora_programa_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMA 1
extern  salida * suma_1();
extern  salida * suma_1_svc();
#define RESTA 2
extern  salida * resta_1();
extern  salida * resta_1_svc();
#define MULTIPLICACION 3
extern  salida * multiplicacion_1();
extern  salida * multiplicacion_1_svc();
#define DIVISION 4
extern  salida * division_1();
extern  salida * division_1_svc();
extern int calculadora_programa_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_entrada (XDR *, entrada*);
extern  bool_t xdr_salida (XDR *, salida*);

#else /* K&R C */
extern bool_t xdr_entrada ();
extern bool_t xdr_salida ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
