/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"
#include <stdio.h>
#include <time.h>

int seleccionarTipoEntrada();
int getOperacion();
int getOperando(int operacion, int i);
struct entrada inParam;
struct t_operandos
{
	int operando1;
	int operando2;
};
void mostrarResultado(entrada inParam, salida resultado);
int sumar(struct t_operandos operandos);

salida calculadora_programa_1(char *host);

int main(int argc, char *argv[])
{

	char *host;

	if (argc < 2)
	{
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];

	//Seleccionar entrada manual o entrada desde fichero
	int seleccionTipoEntrada = seleccionarTipoEntrada();

	switch (seleccionTipoEntrada)
	{
	case 1:
	{
		inParam.operacion = getOperacion();
		inParam.operando1 = getOperando(inParam.operacion, 1);
		inParam.operando2 = getOperando(inParam.operacion, 2);
		calculadora_programa_1(host);
		printf("\n");
		printf("Fin del programa...");
		printf("\n");
		printf("\n");
	}
	break;
	case 2:
	{
		FILE *fichero;
		struct t_operandos operandos;
		fichero = fopen("datos.dat", "rb");

		if (fichero == NULL)
		{
			printf("Error: No se ha podido abrir el archivo datos.dat");
		}
		else
		{
			clock_t tiempoInicial, tiempoFinal;
			double segundos;
			tiempoInicial = clock();
			int i = 0;

			do
			{
				fread(&operandos, sizeof(operandos), 1, fichero);
				int resultado = sumar(operandos);
				printf("Suma: %i + %i = %i\n", operandos.operando1, operandos.operando2, resultado);
				i++;
			} while (feof(fichero) == 0);

			tiempoFinal = clock();
			segundos = (double)(tiempoFinal - tiempoInicial) / CLOCKS_PER_SEC;
			printf("\n");
			printf("\n");
			printf("===================================================================\n");
			printf("El tiempo de sumar %i números es de %f segundos.\n", i, segundos);
			printf("===================================================================\n");
			printf("\n");
			printf("Fin del programa...");
			printf("\n");
			printf("\n");
		}
	}
	break;
	case 3:
	{
		FILE *fichero;
		struct t_operandos operandos;
		fichero = fopen("datos.dat", "rb");

		if (fichero == NULL)
		{
			printf("Error: No se ha podido abrir el archivo datos.dat");
		}
		else
		{
			clock_t tiempoInicial, tiempoFinal;
			double segundos;
			tiempoInicial = clock();
			int i = 0;

			do
			{
				fread(&operandos, sizeof(operandos), 1, fichero);
				inParam.operacion = 1;
				inParam.operando1 = operandos.operando1;
				inParam.operando2 = operandos.operando2;
				calculadora_programa_1(host);
				i++;
			} while (feof(fichero) == 0);

			tiempoFinal = clock();
			segundos = (double)(tiempoFinal - tiempoInicial) / CLOCKS_PER_SEC;
			printf("\n");
			printf("\n");
			printf("===================================================================\n");
			printf("El tiempo de sumar %i números es de %f segundos.\n", i, segundos);
			printf("===================================================================\n");
			printf("\n");
			printf("Fin del programa...");
			printf("\n");
			printf("\n");
		}
	}
	break;
	}

	exit(0);
}

salida
calculadora_programa_1(char *host)
{
	CLIENT *clnt;

	salida *result_1;
	entrada suma_1_arg = inParam;
	salida *result_2;
	entrada resta_1_arg = inParam;
	salida *result_3;
	entrada multiplicacion_1_arg = inParam;
	salida *result_4;
	entrada division_1_arg = inParam;
	salida *resultado;

#ifndef DEBUG
	clnt = clnt_create(host, CALCULADORA_PROGRAMA, CALCULADORA_VERSION, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */

	switch (inParam.operacion)
	{
	case 1:
	{
		result_1 = suma_1(&suma_1_arg, clnt);
		if (result_1 == (salida *)NULL)
		{
			clnt_perror(clnt, "Fallo en la comunicación...");
		}
		resultado = result_1;
	}
	break;
	case 2:
	{
		result_2 = resta_1(&resta_1_arg, clnt);
		if (result_2 == (salida *)NULL)
		{
			clnt_perror(clnt, "Fallo en la comunicación...");
		}
		resultado = result_2;
	}
	break;
	case 3:
	{
		result_3 = multiplicacion_1(&multiplicacion_1_arg, clnt);
		if (result_3 == (salida *)NULL)
		{
			clnt_perror(clnt, "Fallo en la comunicación...");
		}
		resultado = result_3;
	}
	break;
	case 4:
	{
		result_4 = division_1(&division_1_arg, clnt);
		if (result_4 == (salida *)NULL)
		{
			clnt_perror(clnt, "Fallo en la comunicación...");
		}
		resultado = result_4;
	}
	break;
	}

#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */

	switch (inParam.operacion)
	{
	case 1:
	{
		printf("\n");
		printf("Resultado: %i + %i = %i", inParam.operando1, inParam.operando2, resultado->resultado);
		printf("\n");
	}
	break;

	case 2:
	{
		printf("\n");
		printf("Resultado: %i - %i = %i", inParam.operando1, inParam.operando2, resultado->resultado);
		printf("\n");
	}
	break;
	case 3:
	{
		printf("\n");
		printf("Resultado: %i * %i = %i", inParam.operando1, inParam.operando2, resultado->resultado);
		printf("\n");
	}
	break;
	case 4:
	{
		printf("\n");
		printf("Resultado: %i / %i = %i y el resto es = %i", inParam.operando1, inParam.operando2, resultado->resultado, resultado->resultado2);
		printf("\n");
	}
	break;
	}
	printf("\n");
}

int seleccionarTipoEntrada()
{
	int opcion;
	int validador = 0;

	do
	{
		system("clear");
		printf("===================================================================\n");
		printf("|              Introduce el tipo de operación                     |\n");
		printf("===================================================================\n");
		printf("\n");
		printf("1.- Entrada manual de parámetros.\n");
		printf("2.- 1000 sumas en local, con los datos introducidos desde archivo.\n");
		printf("3.- 1000 sumas en remoto, con los datos introducidos desde archivo.\n");
		printf("\n");
		printf("¿Opción? = ");
		fflush(stdin);
		scanf("%d", &opcion);
		fflush(stdin);

		if (opcion >= 1 && opcion <= 3)
		{
			validador = 1;
		}

	} while (validador == 0);

	return opcion;
}

int getOperacion()
{
	int opcion;
	int validador = 0;

	do
	{
		system("clear");
		printf("===================================================================\n");
		printf("|              Introduce la operación a realizar                  |\n");
		printf("===================================================================\n");
		printf("\n");
		printf("1.- Suma.\n");
		printf("2.- Resta.\n");
		printf("3.- Multiplicación.\n");
		printf("4.- División Entera.\n");
		printf("\n");
		printf("¿Opción? = ");
		fflush(stdin);
		scanf("%d", &opcion);
		fflush(stdin);

		if (opcion >= 1 && opcion <= 4)
		{
			validador = 1;
		}

	} while (validador == 0);

	return opcion;
}

int getOperando(int operacion, int i)
{
	int operando;

	int validador = 0;

	do
	{

		system("clear");
		printf("====================================\n");
		printf("   Introduce el operando %i\n", i);
		printf("====================================\n");
		printf("\n");
		printf("\n");
		printf("Operando %i ? = ", i);
		fflush(stdin);
		scanf("%i", &operando);
		fflush(stdin);
		if (operacion == 4 && operando == 0)
		{
			validador = 0;
		}
		else
		{
			validador = 1;
		}

	} while (validador == 0);

	return operando;
}

void mostrarResultado(entrada inParam, salida resultado)
{

	system("clear");
	printf("====================================\n");
	printf("       Resultado\n");
	printf("====================================\n");
	printf("\n");
	printf("\n");

	switch (inParam.operacion)
	{
	case 1:
	{
		printf("%i + %i = %i", inParam.operando1, inParam.operando2, resultado.resultado);
	}
	break;

	case 2:
	{
		printf("%i - %i = %i", inParam.operando1, inParam.operando2, resultado.resultado);
	}
	break;
	case 3:
	{
		printf("%i * %i = %i", inParam.operando1, inParam.operando2, resultado.resultado);
	}
	break;
	case 4:
	{
		printf("%i / %i = %i y el resto es = %i", inParam.operando1, inParam.operando2, resultado.resultado, resultado.resultado2);
	}
	break;
	}
}

int sumar(struct t_operandos oper)
{

	return oper.operando1 + oper.operando2;
}